
name: Node.js CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: 拉取代码
      - name: 配置环境变量
        run: export DOCKER_BUILDKIT=1
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: 登录并编译dockerfile
        with:
          image: inyaa/inyaw-next
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: ssh远程部署
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            sudo docker stop $(sudo docker ps -a | grep "inyaw-next" | awk '{print $1}')
            sudo docker rm -f $(sudo docker ps -a | grep inyaw-next | awk '{print $1}')
            sudo docker rmi $(sudo docker images | grep inyaw-next | awk '{print $3}')
            sudo docker run -d -p 3000:3000 --name inyaw-next --network inyaw --network-alias inyaw-next inyaa/inyaw-next:latest
