
name: Node.js CI

on:
  push:
    branches: [ shadcn ]
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: 拉取代码
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: 登录并编译dockerfile
        with:
          image: inyaa/inyaw-next
          tags: latest
          registry: ccr.ccs.tencentyun.com
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: ssh远程部署
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker stop $(sudo docker ps -a | grep "inyaw-next" | awk '{print $1}')
            docker rm -f $(sudo docker ps -a | grep inyaw-next | awk '{print $1}')
            docker rmi $(sudo docker images | grep inyaw-next | awk '{print $3}')
            docker run -d -p 3000:3000 --name inyaw-next --network inyaw --network-alias inyaw-next ccr.ccs.tencentyun.com/inyaa/inyaw-next:latest
