
name: Node.js CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: inyaw/inyaw-next
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            sudo docker stop $(sudo docker ps -a | grep "inyaw-next" | awk '{print $1}')
            sudo docker rm -f $(sudo docker ps -a | grep inyaw-next | awk '{print $1}')
            sudo docker rmi $(sudo docker images | grep inyaw-next | awk '{print $3}')
            sudo docker run -d -p 3000:3000 --name inyaw-next --network inyaw --network-alias inyaw-next inyaa/inyaw-next:latest
